live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.5

[colors.normal]
black = '0x4c4f69'
red = '0xea999c'
green = '0x40a02b'
yellow = '0xe5c890'
blue = '0x8caaee'
magenta = '0xca9ee6'
cyan = '0x209fb5'
white = '0xdce0e8'

[colors.bright]
black = '0x4c4f69'
red = '0xea999c'
green = '0x40a02b'
yellow = '0xe5c890'
blue = '0x8caaee'
magenta = '0xca9ee6'
cyan = '0x209fb5'
white = '0xdce0e8'

[colors.selection]
background = '0x4c4f69'
foreground = '0xdce0e8'

[colors.primary]
background = '0x000000'
foreground = '0xFFFFFF'

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Heavy"

[font.bold_italic]
family = "Fira Code"
style = "Heavy Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Medium"
